version: '3.7'
services:
  guidy_recommender:
    build:
      context: ./
    container_name: "guidy-recommender"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./:/usr/src/app
    ports:
    - "8086:8086"
    command: gunicorn -b 0.0.0.0:8086  app:app
    



